name: github_repo_viewer
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  auto_route: ^4.0.1
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.0.3
  flash: ^2.0.3+2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.5
  flutter_riverpod: ^1.0.4
  flutter_secure_storage: ^5.0.2
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  lottie: ^1.3.0
  material_design_icons_flutter: ^5.0.6595
  material_floating_search_bar: ^0.3.7
  oauth2: ^2.0.0
  path: ^1.8.1
  path_provider: ^2.0.11
  sembast: ^3.2.0+1
  shimmer: ^2.0.0
  url_launcher: ^6.1.4
  webview_flutter: ^3.0.4

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  lint: ^1.8.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/launcher/
    - assets/animations/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
